(deftheme nnn
  "Created 2021-03-29.")

(custom-theme-set-faces
 'nnn
 '(default ((t (:family "Source Code Pro" :foundry "ADBO" :width normal :height 127 :weight normal :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#f8f8f8" :background "#1c1c1c" :stipple nil :inherit nil))))
 '(cursor ((t (:foreground "#a7a7a7" :background "#F8F8F0"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#F0DFAF"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#f8f8f8"))))
 '(highlight ((t (:foreground "#11111" :background "#27292a"))))
 '(region ((t (:extend t :background "#403D3D"))))
 '(shadow ((t (:foreground "#465457"))))
 '(secondary-selection ((t (:extend t :background "#424242"))))
 '(trailing-whitespace ((t (:foreground "#d0bf8f" :background "#94bff3"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#CACACA"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#868686"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#5F5A60"))))
 '(font-lock-constant-face ((t (:foreground "#CF6A4C"))))
 '(font-lock-doc-face ((t (:slant italic :foreground "#868686"))))
 '(font-lock-function-name-face ((t (:slant italic :foreground "#9B703F"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#CDA869"))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#868686"))))
 '(font-lock-preprocessor-face ((t (:foreground "Aquamarine"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#E9C06"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "red"))))
 '(font-lock-string-face ((t (:foreground "#8F9D6A"))))
 '(font-lock-type-face ((t (:foreground "#9B703F"))))
 '(font-lock-variable-name-face ((t (:foreground "#f8f8f8"))))
 '(font-lock-warning-face ((t (:background "red" :foreground "white" :weight bold))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#6ca0a3"))))
 '(link-visited ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#dc8cc3"))))
 '(fringe ((t (:width normal :foreground "#453d41" :background "#303030"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#F0DFAF" :background "#000000" :inherit (mode-line)))))
 '(tooltip ((t (:foreground "#DCDCCC" :background "#4F4F4F"))))
 '(mode-line ((t (:box nil :foreground "grey75" :background "#282828"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "aquamarine" :background "#282828"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#e6e6e6"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#CF6A4C"))))
 '(mode-line-inactive ((t (:box nil :foreground "black" :background "#282828"))))
 '(isearch ((t (:weight bold :inverse-video t :foreground "#e6e6e6" :background "#5F5F5F"))))
 '(isearch-fail ((t (:inverse-video t :foreground "#8c5353" :background "#b6b6b6"))))
 '(lazy-highlight ((t (:weight bold :inverse-video t :foreground "#868686" :background "#383838"))))
 '(match ((t (:weight bold :inverse-video t :foreground "#e6e6e6" :background "#2B2B2B"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'nnn)
